---

plugins:
  - jest

# https://eslint.org/docs/user-guide/configuring#specifying-environments
env:
  node: true

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'

parserOptions:
  ecmaVersion: latest

rules:
  no-console: "off"
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]